hub:
  world_name: "piatto"

# Configurazione kit
kit:
  # Mondo in cui è possibile modificare i kit
  edit_world: "piatto"

# Messaggi del plugin
messaggi:
  no_permission: "&cNon hai il permesso per eseguire questo comando!"
  reload_done: "&aConfig ricaricata con successo!"
  party_not_found: "&cNon sei in una party o la party non è stata trovata!"
  party_too_small: "&cLa tua party deve avere almeno {min} membri per iniziare un raid!"
  party_too_big: "&cLa tua party ha troppi membri! Massimo {max} membri per raid."
  not_party_leader: "&cSolo il leader della party può iniziare un raid!"
  party_members_not_online: "&cTutti i membri della party devono essere online per iniziare un raid!"

  # Nuovi messaggi per statistiche
  stats_reset_success: "&aStatistiche di &e{player} &aresettate con successo!"
  stats_reset_player_not_found: "&cGiocatore &e{player} &cnon trovato o senza statistiche!"
  stats_reset_notification: "&6Le tue statistiche raid sono state resettate da un amministratore."
  no_stats_available: "&c{player} non ha ancora completato nessun raid!"

# Configurazione party
party:
  min_members: 2
  max_members: 6
  require_leader: true  # Solo il leader può iniziare un raid

# Kit predefinito che viene dato ai giocatori che non hanno un kit salvato
# Formato: MATERIAL:QUANTITA:DURABILITY:INCANTESIMI
default_kit:
  enabled: true
  display_name: "Kit Base"
  items:
    - "IRON_SWORD:1:0:sharpness:2"
    - "COOKED_BEEF:16:0"
    - "GOLDEN_APPLE:3:0"
    - "SHIELD:1:0"
    - "BOW:1:0:power:2"
    - "ARROW:64:0"
  # Armatura separata per maggiore chiarezza
  armor:
    helmet: "IRON_HELMET:1:0:protection:1"
    chestplate: "IRON_CHESTPLATE:1:0:protection:1"
    leggings: "IRON_LEGGINGS:1:0:protection:1"
    boots: "IRON_BOOTS:1:0:protection:1,feather_falling:2"

# Comandi globali eseguiti dalla console per tutti i mondi al completamento di un raid
# Placeholder disponibili: {player}, {world}, {uuid}
global_console_commands:
  - "say {player} ha completato un raid nel mondo {world}!"
  - "give {player} minecraft:diamond 5"

# Configurazione dei mondi
worlds:
  mondo1:
    world_name: "Cybertrunk_City"
    display_name: "Nether Adventure"
    spawn:
      x: 485
      y: 208
      z: -307
    exit:
      x: 490
      y: 208
      z: -307
    # Comandi specifici per questo mondo
    # Placeholder disponibili: {player}, {world}, {uuid}
    console_commands:
      - "give {player} minecraft:netherite_ingot 1"
      - "xp add {player} 100"

  mondo2:
    world_name: "world_the_end"
    display_name: "End Challenge"
    spawn:
      x: 100.5
      y: 50.0
      z: 0.5
    exit:
      x: 120.5
      y: 50.0
      z: 20.5
    console_commands:
      - "give {player} minecraft:elytra 1"
      - "give {player} minecraft:ender_pearl 16"
      - "title {player} title {\"text\":\"End Conqueror!\",\"color\":\"purple\"}"

  mondo3:
    world_name: "custom_world"
    display_name: "Mondo Personalizzato"
    spawn:
      x: -50.5
      y: 70.0
      z: 200.5
    exit:
      x: -30.5
      y: 70.0
      z: 220.5
    console_commands:
      - "give {player} minecraft:golden_apple 3"
      - "effect give {player} minecraft:regeneration 30 2"